# Generated by Django 4.0.1 on 2022-12-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='username',
        ),
        migrations.AddField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
